# Generated by Django 5.1.1 on 2024-09-25 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_patient_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="specialty",
            new_name="specialization",
        ),
    ]
