# Generated by Django 5.1.1 on 2024-09-25 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rename_specialization_doctor_speciality"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="speciality",
            new_name="specialty",
        ),
    ]
