# Generated by Django 5.1.1 on 2024-09-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_rename_speciality_doctor_specialty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="appointment_fee",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="specialty",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="doctor",
        ),
        migrations.AddField(
            model_name="doctor",
            name="name",
            field=models.CharField(default="Unnamed Doctor", max_length=255),
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(default="General", max_length=255),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="patient",
            name="sex",
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name="HospitalAdmin",
        ),
    ]
