# Generated by Django 5.1.1 on 2024-10-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_patient_sex_medicine_prescription"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalMedicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("unique_code", models.CharField(max_length=7, unique=True)),
                ("code_confirmed", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="category",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="company",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="name",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="unique_code",
        ),
        migrations.AddField(
            model_name="medicine",
            name="global_medicine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.globalmedicine",
            ),
        ),
    ]
